ANALYZE TABLE SYS.CYCLISTIC_TRIP_DATA_RAW_T COMPUTE STATISTICS;
-- ANALYZE TABLE SYS.CYCLISTIC_TRIP_DATA_RAW_T ESTIMATE STATISTICS 1000 ROWS; -- Faulty script?
-- ANALYZE TABLE SYS.CYCLISTIC_TRIP_DATA_RAW_T ESTIMATE STATISTICS 50 PERCENT; -- Untested.

/*
BEGIN
DBMS_STATS.GATHER_TABLE_STATS('SYS', 'CYCLISTIC_TRIP_DATA_RAW_T', ESTIMATE_PERCENT => 50, BLOCK_SAMPLE => TRUE, DEGREE => 4);
END;
*/

SELECT Q'<SELECT * FROM >'||OWNER||Q'<.>'||OBJECT_NAME||Q'<;>' TEXT_SCRIPT
FROM SYS.ALL_OBJECTS
WHERE UPPER(OWNER) = 'SYS'
AND UPPER(OBJECT_TYPE) IN ('TABLE', 'VIEW')
AND UPPER(OBJECT_NAME) LIKE 'ALL%TAB%STAT%'
;

SELECT * FROM SYS.ALL_TAB_STATISTICS WHERE UPPER(TABLE_NAME) = 'CYCLISTIC_TRIP_DATA_RAW_T';
SELECT * FROM SYS.ALL_TAB_COL_STATISTICS WHERE UPPER(TABLE_NAME) = 'CYCLISTIC_TRIP_DATA_RAW_T';

SELECT * FROM SYS.ALL_TAB_COL_STAT_MODELS;
SELECT * FROM SYS.ALL_TAB_HISTGRM_PENDING_STATS;
SELECT * FROM SYS.ALL_TAB_PENDING_STATS;
SELECT * FROM SYS.ALL_TAB_STATS_HISTORY;
SELECT * FROM SYS.ALL_TAB_STAT_PREFS;

SELECT TRUNC(STARTED_AT, 'MM') MONTH_STARTED
     , COUNT(*) CNT_ROW
-- SELECT *
FROM SYS.CYCLISTIC_TRIP_DATA_RAW_T
GROUP BY TRUNC(STARTED_AT, 'MM')
ORDER BY TRUNC(STARTED_AT, 'MM') ASC
;

WITH RAW_DATA AS (
SELECT /*+MATERIALIZE*/
       RIDE_ID
     , RIDEABLE_TYPE
     , TO_CHAR(STARTED_AT, 'DAY') DAY_OF_WEEK
     , TRUNC(STARTED_AT, 'MM') MONTH_STARTED
     , TRUNC(STARTED_AT, 'IW') WEEK_STARTED
     , TRUNC(STARTED_AT) DATE_STARTED
     , STARTED_AT DTIME_STARTED
     , ENDED_AT DTIME_ENDED
--   , ENDED_AT - STARTED_AT DURATION
     , CAST(ENDED_AT AS DATE) - CAST(STARTED_AT AS DATE) DURATION
     , START_STATION_NAME
     , START_STATION_ID
     , END_STATION_NAME
     , END_STATION_ID
     , START_LAT
     , START_LNG
     , END_LAT
     , END_LNG
     , MEMBER_CASUAL 
FROM SYS.CYCLISTIC_TRIP_DATA_RAW_T
)

SELECT /*+USE_HASH_AGGREGATION*/
       'MONTHLY' COVERAGE
     , MONTH_STARTED DATE_COVERED
     , MEMBER_CASUAL
     , COUNT(*) CNT_RIDE
     , AVG(DURATION) AVG_DURATION
FROM RAW_DATA
GROUP BY 'MONTHLY', MONTH_STARTED, MEMBER_CASUAL

UNION ALL

SELECT /*+USE_HASH_AGGREGATION*/
       'WEEKLY' COVERAGE
     , WEEK_STARTED DATE_COVERED
     , MEMBER_CASUAL
     , COUNT(*) CNT_RIDE
     , AVG(DURATION) AVG_DURATION
FROM RAW_DATA
GROUP BY 'WEEKLY', WEEK_STARTED, MEMBER_CASUAL

UNION ALL

SELECT /*+USE_HASH_AGGREGATION*/
       'DAILY' COVERAGE
     , DATE_STARTED DATE_COVERED
     , MEMBER_CASUAL
     , COUNT(*) CNT_RIDE
     , AVG(DURATION) AVG_DURATION
FROM RAW_DATA
GROUP BY 'DAILY', DATE_STARTED, MEMBER_CASUAL
;